### ISSUE TITLE
2021版本，第一次构建 报ZipException错误，清除本地仓库也是不行

### ISSUE THREAD

**Issue by alankenan** [Tencent/spring-cloud-tencent#1084]
spring-cloud-tencent-2021.0>.\mvnw.cmd clean package
Exception in thread, main java.util.zip.ZipException: error in opening zip fileat java.util.zip.ZipFile.open(Native Method)at iava.util.zin.ziprile.imit>(zipFile.java:225)at java.util.zip.ZipFile.<init>(zipFile.java:155)at java.util.zip.ZipFile.<init>(zipFile.java:169)
at org.apache.maven, wrapper.Installer.mzip(Installer. java:209)at org. apache.maven. wrapper.Installer.createDist(Instailer.java:102)
at org. apache.maven. wrapper. WrapperExecutor.execute(WrapperExecutor. java:155)at org.apache.maven. wrapper.MavenWirapperllain.main(MavenVrapperMain. java:72)

**Comment by SkyeBeFreeman** [comment]
1. 使用IDEA等IDE打开项目，然后编译打包代码。
2. 参考网上相关解决方案。https://stackoverflow.com/questions/325202/java-util-zip-zipexception-error-in-opening-zip-file
