### ISSUE TITLE
spring cloud网关中使用北极星限流不生效

### ISSUE THREAD

**Issue by zev-223** [Tencent/spring-cloud-tencent#1106]
版本号：
spring-cloud-starter-gateway  2022.0.4 
spring-cloud-starter-tencent-polaris-ratelimit  1.11.9-2022.0.1

spring-cloud-starter-gateway网关中集成北极星限流，匹配限流规则时限流未生效。后台报错信息： java.lang.IllegalArgumentException: Validation failed for header 'internal-callee-activerule' 

限流规则配置
![a](https://gateway.irked.cn/bus/file/data/upload/2023/09/CztLWIsNVx.png)

**Comment by SkyeBeFreeman** [comment]
也发一下限流规则的配置

**Comment by SkyeBeFreeman** [comment]
详细的报错日志贴一下，看起来像是监控上报的时候没有正确读取到生效的限流规则。SCT会在这里塞入生效的限流规则名，然后监控上报时可以上报到北极星。
<img width="922" alt="image" src="https://github.com/Tencent/spring-cloud-tencent/assets/24446200/adbc2490-e17d-4860-979c-be2753ad896f">

**Comment by zev-223** [comment]
> 详细的报错日志贴一下，看起来像是监控上报的时候没有正确读取到生效的限流规则。SCT会在这里塞入生效的限流规则名，然后监控上报时可以上报到北极星。 <img alt="image" width="922" src="https://user-images.githubusercontent.com/24446200/266950736-adbc2490-e17d-4860-979c-be2753ad896f.png">

2023-09-11T16:13:20.857+08:00 ERROR 1 --- [or-http-epoll-4] c.t.c.p.r.f.QuotaCheckReactiveFilter     : fail to invoke getQuota, service is irked-gateway

java.lang.IllegalArgumentException: Validation failed for header 'internal-callee-activerule'
        at io.netty.handler.codec.DefaultHeaders.validateValue(DefaultHeaders.java:1019) ~[netty-codec-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.DefaultHeaders.add(DefaultHeaders.java:330) ~[netty-codec-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:364) ~[netty-codec-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:115) ~[netty-codec-http-4.1.97.Final.jar!/:4.1.97.Final]
        at org.springframework.http.server.reactive.NettyHeadersAdapter.add(NettyHeadersAdapter.java:59) ~[spring-web-6.0.11.jar!/:6.0.11]
        at org.springframework.http.server.reactive.NettyHeadersAdapter.add(NettyHeadersAdapter.java:40) ~[spring-web-6.0.11.jar!/:6.0.11]
        at org.springframework.http.HttpHeaders.add(HttpHeaders.java:1725) ~[spring-web-6.0.11.jar!/:6.0.11]
        at com.tencent.cloud.polaris.ratelimit.filter.QuotaCheckReactiveFilter.filter(QuotaCheckReactiveFilter.java:122) ~[spring-cloud-starter-tencent-polaris-ratelimit-1.11.9-2022.0.1.jar!/:1.11.9-2022.0.1]
        at org.springframework.web.server.handler.DefaultWebFilterChain.invokeFilter(DefaultWebFilterChain.java:114) ~[spring-web-6.0.11.jar!/:6.0.11]
        at org.springframework.web.server.handler.DefaultWebFilterChain.lambda$filter$0(DefaultWebFilterChain.java:108) ~[spring-web-6.0.11.jar!/:6.0.11]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55) ~[reactor-core-3.5.9.jar!/:3.5.9]
        at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:1052) ~[reactor-netty-http-1.1.10.jar!/:1.1.10]
        at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:710) ~[reactor-netty-core-1.1.10.jar!/:1.1.10]
        at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:481) ~[reactor-netty-core-1.1.10.jar!/:1.1.10]
        at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:647) ~[reactor-netty-http-1.1.10.jar!/:1.1.10]
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[reactor-netty-core-1.1.10.jar!/:1.1.10]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:238) ~[reactor-netty-http-1.1.10.jar!/:1.1.10]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[netty-codec-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[netty-transport-classes-epoll-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[netty-transport-classes-epoll-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar!/:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
Caused by: java.lang.IllegalArgumentException: a header value contains prohibited character 0x6d4b at index 0.
        at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueValidator.validate(DefaultHttpHeaders.java:395) ~[netty-codec-http-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueValidator.validate(DefaultHttpHeaders.java:387) ~[netty-codec-http-4.1.97.Final.jar!/:4.1.97.Final]
        at io.netty.handler.codec.DefaultHeaders.validateValue(DefaultHeaders.java:1017) ~[netty-codec-4.1.97.Final.jar!/:4.1.97.Final]
        ... 47 common frames omitted

2023-09-11T16:13:32.056+08:00 ERROR 1 --- [or-http-epoll-1] m.c.DecodeTransferMetadataReactiveFilter : handle metadata[MetadataContext{fragmentContexts={"transitive":{},"disposable":{"source_service_namespace":"irked-cloud-polaris","source_service_name":"irked-gateway"}}}] error.

**Comment by SkyeBeFreeman** [comment]
你这边有直接或者间接引入netty相关依赖吗？我看了下netty的版本不匹配

**Comment by zev-223** [comment]
> 你这边有直接或者间接引入netty相关依赖吗？我看了下netty的版本不匹配

 嗯，的确是netty版本的问题，springcloud 版本降到 2022.0.2 及以下版本就正常了

**Comment by SkyeBeFreeman** [comment]
这个版本问题在下个版本升级2022版本时会关注修复。如果您有兴趣，可以提交PR参与共建。

**Comment by zev-223** [comment]
> 这个版本问题在下个版本升级2022版本时会关注修复。如果您有兴趣，可以提交PR参与共建。

好的，感谢

**Comment by SkyeBeFreeman** [comment]
@zev-223 使用1.12.1-2022.0.4版本的SDK看下能否复现呢？我这里暂时不能复现出来。

**Comment by zev-223** [comment]
> @zev-223 使用1.12.1-2022.0.4版本的SDK看下能否复现呢？我这里暂时不能复现出来。

![a](https://gateway.irked.cn/bus/file/data/upload/2023/09/ZRBYkMQg9p.png)

我试了一下，还是有的
几个核心版本号：
        <spring.cloud.version>2022.0.4</spring.cloud.version>
        <spring.cloud.tencent.version>1.12.1-2022.0.4</spring.cloud.tencent.version>
        <spring.boot.version>3.1.3</spring.boot.version>

**Comment by SkyeBeFreeman** [comment]
问题应该出在spring boot版本为3.1.x，我再试试

**Comment by SkyeBeFreeman** [comment]
> > @zev-223 使用1.12.1-2022.0.4版本的SDK看下能否复现呢？我这里暂时不能复现出来。
> 
> ![a](https://camo.githubusercontent.com/de9486f0373ea4ff8b52eb83f2438a353464a10e14fbef875f009ff7150350f7/68747470733a2f2f676174657761792e69726b65642e636e2f6275732f66696c652f646174612f75706c6f61642f323032332f30392f5a5242596b4d516739702e706e67)
> 
> 我试了一下，还是有的 几个核心版本号： <spring.cloud.version>2022.0.4</spring.cloud.version> <spring.cloud.tencent.version>1.12.1-2022.0.4</spring.cloud.tencent.version> <spring.boot.version>3.1.3</spring.boot.version>

我这边还是没有复现出来。你这个报错是出现在校验头部值的时候出现的，建议发一下你的限流规则名称，并debug到这个方法，io.netty.handler.codec.DefaultHeaders#validateValue，看看是哪个环节校验出问题。

**Comment by zev-223** [comment]
> 问题应该出在spring boot版本为3.1.x，我再试试

本地debug了一下，发现请求头“internal-callee-activerule”，传递的value值为 配置的限流规则名称，如果这个名称为中文时会出现上面的错误

**Comment by SkyeBeFreeman** [comment]
这里我后面验证一下，是否为高版本netty做了校验限制

**Comment by SkyeBeFreeman** [comment]
我这边验证了一下，确实有这个问题。修复方案如下：
1. HTTP头部塞入internal-callee-activerule时，需将value通过UTF-8进行encode。
2. 从HTTP头部取出internal-callee-activerule时，需将value通过UTF-8进行decode。
