### ISSUE TITLE
升级 Grpc-Java 版本后，启动仍旧报错。ERR-1007(NETWORK_ERROR)

### ISSUE THREAD

**Issue by herodotus-ecosystem** [Tencent/spring-cloud-tencent#1212]
目前已经升级了 grpc-java 的版本至 1.59.1。之前的问题已经解决：

[Tencent/spring-cloud-tencent#1210](https://github.com/Tencent/spring-cloud-tencent/issues/1210) [Tencent/spring-cloud-tencent#1209](https://github.com/Tencent/spring-cloud-tencent/issues/1209)

但是会引入新的问题，grpc-java 新版本代码有变化，部分api 改变，导致 polaris 代码无法与之适配。`MetadataUtils.attachHeaders` 找不到

![image](https://github.com/Tencent/spring-cloud-tencent/assets/11025512/615122de-eabe-4fb1-bcfc-8a48d2cad0f9)

具体错误信息如下：

```
com.tencent.polaris.api.exception.RetriableException: ERR-1007(NETWORK_ERROR): failed to load config file. namespace = herodotus, group = sct-quickstart-caller, file = application.yml, cause: 'io.grpc.stub.AbstractStub io.grpc.stub.MetadataUtils.attachHeaders(io.grpc.stub.AbstractStub, io.grpc.Metadata)'
	at com.tencent.polaris.plugins.configuration.connector.polaris.PolarisConfigFileConnector.getConfigFile(PolarisConfigFileConnector.java:85) ~[polaris-configuration-connector-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.internal.RemoteConfigFileRepo.lambda$doPull$0(RemoteConfigFileRepo.java:126) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.api.plugin.filter.ConfigFileFilterChain.execute(ConfigFileFilterChain.java:49) ~[polaris-plugin-api-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.internal.RemoteConfigFileRepo.doPull(RemoteConfigFileRepo.java:126) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.internal.AbstractConfigFileRepo.pull(AbstractConfigFileRepo.java:46) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.internal.RemoteConfigFileRepo.<init>(RemoteConfigFileRepo.java:77) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.internal.ConfigFileManager.createConfigKVFile(ConfigFileManager.java:147) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.internal.ConfigFileManager.getConfigKVFile(ConfigFileManager.java:102) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.flow.DefaultConfigFileFlow.getConfigYamlFile(DefaultConfigFileFlow.java:65) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.DefaultConfigFileService.getConfigYamlFile(DefaultConfigFileService.java:76) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.polaris.configuration.client.DefaultConfigFileService.getConfigYamlFile(DefaultConfigFileService.java:70) ~[polaris-configuration-client-1.14.3.jar:na]
	at com.tencent.cloud.polaris.config.adapter.PolarisConfigFileLocator.loadPolarisPropertySource(PolarisConfigFileLocator.java:223) ~[spring-cloud-starter-tencent-polaris-config-1.12.4-2022.0.4.jar:1.12.4-2022.0.4]
	at com.tencent.cloud.polaris.config.adapter.PolarisConfigFileLocator.initInternalConfigFiles(PolarisConfigFileLocator.java:122) ~[spring-cloud-starter-tencent-polaris-config-1.12.4-2022.0.4.jar:1.12.4-2022.0.4]
	at com.tencent.cloud.polaris.config.adapter.PolarisConfigFileLocator.locate(PolarisConfigFileLocator.java:88) ~[spring-cloud-starter-tencent-polaris-config-1.12.4-2022.0.4.jar:1.12.4-2022.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:50) ~[spring-cloud-context-4.0.4.jar:4.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:46) ~[spring-cloud-context-4.0.4.jar:4.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.doInitialize(PropertySourceBootstrapConfiguration.java:121) ~[spring-cloud-context-4.0.4.jar:4.0.4]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:111) ~[spring-cloud-context-4.0.4.jar:4.0.4]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:611) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:391) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.6.jar:3.1.6]
	at com.example.SpringCloudTencentTestApplication.main(SpringCloudTencentTestApplication.java:12) ~[classes/:na]
Caused by: java.lang.NoSuchMethodError: 'io.grpc.stub.AbstractStub io.grpc.stub.MetadataUtils.attachHeaders(io.grpc.stub.AbstractStub, io.grpc.Metadata)'
	at com.tencent.polaris.plugins.connector.grpc.GrpcUtil.attachRequestHeader(GrpcUtil.java:132) ~[connector-polaris-grpc-1.14.3.jar:na]
	at com.tencent.polaris.plugins.configuration.connector.polaris.PolarisConfigFileConnector.getConfigFile(PolarisConfigFileConnector.java:73) ~[polaris-configuration-connector-1.14.3.jar:na]
	... 23 common frames omitted
```

**Comment by SkyeBeFreeman** [comment]
这个问题已经在新版本的polaris-java修复了，https://github.com/polarismesh/polaris-java/pull/447 ，敬请期待正式版发布。
