### ISSUE TITLE
如果使用EnvironmentPostProcessor配置字段为null，启动会报错

### ISSUE THREAD

**Issue by SkyeBeFreeman** [Tencent/spring-cloud-tencent#1282]
**Describe the bug**

```java
public class MqEnvPostProcessor implements EnvironmentPostProcessor {
	@Override
	public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
		Map<String, Object> defaultProperties = new HashMap<>();
		defaultProperties.put("my.key", null);
		MapPropertySource propertySource = new MapPropertySource("myenv", defaultProperties);
		environment.getPropertySources().addFirst(propertySource);
	}
}
```

异常日志：

```
2024-04-22 15:11:59.075  INFO 69694 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-04-22 15:11:59.085  INFO 69694 --- [           main] c.t.c.p.registry.PolarisServiceRegistry  : De-registering from Polaris Server now...
2024-04-22 15:11:59.117  INFO 69694 --- [           main] c.t.c.p.registry.PolarisServiceRegistry  : De-registration finished.
2024-04-22 15:12:00.169 ERROR 69694 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.0.1-jre.jar:na]
	at com.google.common.cache.LocalCache.put(LocalCache.java:4242) ~[guava-32.0.1-jre.jar:na]
	at com.google.common.cache.LocalCache.putAll(LocalCache.java:4290) ~[guava-32.0.1-jre.jar:na]
	at com.google.common.cache.LocalCache$LocalManualCache.putAll(LocalCache.java:4941) ~[guava-32.0.1-jre.jar:na]
	at com.tencent.cloud.polaris.config.listener.PolarisConfigListenerContext.initialize(PolarisConfigListenerContext.java:119) ~[classes/:na]
	at com.tencent.cloud.polaris.config.listener.PolarisConfigChangeEventListener.onApplicationEvent(PolarisConfigChangeEventListener.java:75) ~[classes/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:429) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:386) ~[spring-context-5.3.31.jar:5.3.31]
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:108) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:78) ~[spring-boot-2.7.18.jar:2.7.18]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:78) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.18.jar:2.7.18]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.18.jar:2.7.18]
	at com.tencent.cloud.quickstart.callee.QuickstartCalleeServiceA.main(QuickstartCalleeServiceA.java:32) ~[classes/:na]
```

**Environment**
- Version: [1.13.1-2021.0.9](https://github.com/Tencent/spring-cloud-tencent/releases/tag/1.13.1-2021.0.9)

**Comment by SkyeBeFreeman** [comment]
closed https://github.com/Tencent/spring-cloud-tencent/commit/8159888db2922c1765f9d9eae72928746240f5f9
