### ISSUE TITLE
服务心跳上报异常(API_TIMEOUT)

### ISSUE THREAD

**Issue by ztaoge** [Tencent/spring-cloud-tencent#148]
使用北极星上报心跳的时候，部分服务出现上报异常，异常日志如下：
2022-05-09 15:13:52 2022-05-09 15:13:52.977 [] [polaris-spring-cloud-heartbeat-1] ERROR com.tencent.cloud.polaris.registry.PolarisServiceRegistry - polaris heartbeat[API_TIMEOUT]
2022-05-09 15:13:52 com.tencent.polaris.api.exception.PolarisException: ERR-1004(API_TIMEOUT), heartbeat request timeout.
2022-05-09 15:13:52 	at com.tencent.polaris.discovery.client.api.DefaultProviderAPI.heartbeat(DefaultProviderAPI.java:153)
2022-05-09 15:13:52 	at com.tencent.cloud.polaris.registry.PolarisServiceRegistry.lambda$heartbeat$0(PolarisServiceRegistry.java:219)
2022-05-09 15:13:52 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2022-05-09 15:13:52 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
2022-05-09 15:13:52 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
2022-05-09 15:13:52 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
2022-05-09 15:13:52 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2022-05-09 15:13:52 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2022-05-09 15:13:52 	at java.lang.Thread.run(Thread.java:750)

使用的包版本是1.4.1-Hoxton.SR9。引入的以下两个starter:
spring-cloud-starter-tencent-polaris-discovery
spring-cloud-starter-tencent-polaris-router

**Comment by SkyeBeFreeman** [comment]
@ztaoge 是否出现warn日志“heartbeat request error, retrying.”呢？

**Comment by ztaoge** [comment]
> @ztaoge 是否出现warn日志“heartbeat request error, retrying.”呢？

没有，就只有这个error日志

**Comment by SkyeBeFreeman** [comment]
> 

添加以下依赖用于二次寻址
`<dependency>
    <groupId>com.tencent.polaris</groupId>
    <artifactId>router-nearby</artifactId>
</dependency>
<dependency>
    <groupId>com.tencent.polaris</groupId>
    <artifactId>router-metadata</artifactId>
</dependency>`

**Comment by SkyeBeFreeman** [comment]
> > @ztaoge 是否出现warn日志“heartbeat request error, retrying.”呢？
> 
> 没有，就只有这个error日志

添加以下依赖用于二次寻址
`<dependency>
    <groupId>com.tencent.polaris</groupId>
    <artifactId>router-nearby</artifactId>
</dependency>
<dependency>
    <groupId>com.tencent.polaris</groupId>
    <artifactId>router-metadata</artifactId>
</dependency>`
