### ISSUE TITLE
心跳上报异常 (client api is not open)

### ISSUE THREAD

**Issue by ranan05** [Tencent/spring-cloud-tencent#1489]
**Describe the bug**
心跳上报失败

**Environment**
版本：2.0.0.0-2022.0.5

**Additional context**

com.tencent.polaris.api.exception.PolarisException: ERR-1006(SERVER_USER_ERROR): server error 400401: client api is not open
	at com.tencent.polaris.plugins.connector.grpc.GrpcUtil.checkResponse(GrpcUtil.java:218) ~[connector-polaris-grpc-2.0.0.0.jar:na]
	at com.tencent.polaris.plugins.connector.grpc.GrpcConnector.heartbeat(GrpcConnector.java:529) ~[connector-polaris-grpc-2.0.0.0.jar:na]
	at com.tencent.polaris.plugins.connector.composite.CompositeConnector.heartbeat(CompositeConnector.java:208) ~[connector-composite-2.0.0.0.jar:na]
	at com.tencent.polaris.discovery.client.flow.DefaultDiscoveryFlow.heartbeat(DefaultDiscoveryFlow.java:222) ~[polaris-discovery-client-2.0.0.0.jar:na]
	at com.tencent.polaris.discovery.client.flow.RegisterFlow.doRunHeartbeat(RegisterFlow.java:85) ~[polaris-discovery-client-2.0.0.0.jar:na]
	at com.tencent.polaris.discovery.client.flow.RegisterFlow.lambda$registerInstance$0(RegisterFlow.java:67) ~[polaris-discovery-client-2.0.0.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

**Comment by SkyeBeFreeman** [comment]
看一下北极星地址如何配置的？

**Comment by ranan05** [comment]
用的是北极星国内公共集群，address: grpc://11.154.192.97:8081
注册都是是成功的，就是心跳上报失败
@SkyeBeFreeman

**Comment by SkyeBeFreeman** [comment]
@ranan05 依赖树和完整的配置文件发一下呢？还有polaris.log文件

**Comment by ranan05** [comment]
spring:
  application:
    name: polaris-test-service1
  cloud:
    polaris:
      address: grpc://11.154.192.97:8081
      discovery:
        token: dd5135f99dae4bb4b6d8624dc2fcxxxx
        namespace: Test
      namespace: Test 
 
 % mvn dependency:tree   
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< com.wy:polaris-demo >-------------------------
[INFO] Building polaris-demo 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- dependency:3.3.0:tree (default-cli) @ polaris-demo ---
[INFO] com.wy:polaris-demo:jar:0.0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:3.0.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:3.0.0:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.15.3:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.15.3:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.15.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.15.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.15.3:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.15.3:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:3.0.0:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.1:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.1:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:10.1.1:compile
[INFO] |  +- org.springframework:spring-web:jar:6.0.21:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:6.0.21:compile
[INFO] |  |  \- io.micrometer:micrometer-observation:jar:1.11.12:compile
[INFO] |  |     \- io.micrometer:micrometer-commons:jar:1.11.12:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:6.0.21:compile
[INFO] |     +- org.springframework:spring-aop:jar:6.0.21:compile
[INFO] |     +- org.springframework:spring-context:jar:6.0.21:compile
[INFO] |     \- org.springframework:spring-expression:jar:6.0.21:compile
[INFO] +- com.tencent.cloud:spring-cloud-starter-tencent-polaris-discovery:jar:2.0.0.0-2022.0.5:compile
[INFO] |  +- com.tencent.cloud:spring-cloud-tencent-rpc-enhancement:jar:2.0.0.0-2022.0.5:compile
[INFO] |  |  +- com.tencent.cloud:spring-cloud-tencent-polaris-context:jar:2.0.0.0-2022.0.5:compile
[INFO] |  |  |  +- com.tencent.cloud:spring-cloud-tencent-commons:jar:2.0.0.0-2022.0.5:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-metadata:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:polaris-threadlocal:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.cloud:spring-cloud-starter-tencent-threadlocal-plugin:jar:2.0.0.0-2022.0.5:compile
[INFO] |  |  |  |  +- org.springframework.boot:spring-boot-configuration-processor:jar:3.0.0:compile
[INFO] |  |  |  |  +- org.springframework.boot:spring-boot-starter-validation:jar:3.0.0:compile
[INFO] |  |  |  |  |  \- org.hibernate.validator:hibernate-validator:jar:8.0.0.Final:compile
[INFO] |  |  |  |  |     +- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] |  |  |  |  |     +- org.jboss.logging:jboss-logging:jar:3.5.0.Final:compile
[INFO] |  |  |  |  |     \- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  |  |  \- com.google.code.gson:gson:jar:2.9.1:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-discovery-factory:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-discovery-client:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:polaris-discovery-api:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:router-isolated:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:router-common:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:router-healthy:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:router-lane:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:loadbalancer-roundrobin:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-circuitbreaker-client:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:polaris-circuitbreaker-api:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:healthchecker-http:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:healthchecker-tcp:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:healthchecker-udp:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:location-provider-base:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:location-provider-local:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:location-provider-remotehttp:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:location-provider-remoteservice:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:event-logger:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-circuitbreaker-factory:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:router-nearby:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:router-metadata:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:circuitbreaker-errrate:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:circuitbreaker-common:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:circuitbreaker-errcount:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:circuitbreaker-composite:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-ratelimit-factory:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-ratelimit-client:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:polaris-ratelimit-api:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:router-rule:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:ratelimiter-reject:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:ratelimiter-common:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:ratelimiter-unirate:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:ratelimiter-reject-concurrency:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:ratelimiter-tsf:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-auth-factory:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-auth-client:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:polaris-auth-api:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:auth-block-allow-list:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-client:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-logging:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:polaris-config-default:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-plugin-api:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:connector-polaris-grpc:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:connector-common:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  |  |  |  +- io.grpc:grpc-all:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-api:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-auth:jar:1.64.0:compile
[INFO] |  |  |  |  |  |  \- com.google.auth:google-auth-library-credentials:jar:1.22.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-core:jar:1.64.0:compile
[INFO] |  |  |  |  |  |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  |  |  |  |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.23:runtime
[INFO] |  |  |  |  |  |  +- io.perfmark:perfmark-api:jar:0.26.0:runtime
[INFO] |  |  |  |  |  |  \- io.grpc:grpc-context:jar:1.64.0:runtime
[INFO] |  |  |  |  |  +- io.grpc:grpc-grpclb:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-inprocess:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-netty:jar:1.64.0:compile
[INFO] |  |  |  |  |  |  +- io.netty:netty-codec-http2:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  +- io.netty:netty-common:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  +- io.netty:netty-buffer:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  +- io.netty:netty-transport:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  |  \- io.netty:netty-resolver:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  +- io.netty:netty-codec:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  +- io.netty:netty-handler:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  |  \- io.netty:netty-codec-http:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  |  +- io.netty:netty-handler-proxy:jar:4.1.110.Final:runtime
[INFO] |  |  |  |  |  |  |  \- io.netty:netty-codec-socks:jar:4.1.110.Final:runtime
[INFO] |  |  |  |  |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.110.Final:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-okhttp:jar:1.64.0:compile
[INFO] |  |  |  |  |  |  \- com.squareup.okio:okio:jar:3.4.0:runtime
[INFO] |  |  |  |  |  |     \- com.squareup.okio:okio-jvm:jar:3.4.0:runtime
[INFO] |  |  |  |  |  |        +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.8.22:runtime
[INFO] |  |  |  |  |  |        |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.8.22:runtime
[INFO] |  |  |  |  |  |        |  |  \- org.jetbrains:annotations:jar:13.0:runtime
[INFO] |  |  |  |  |  |        |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.8.22:runtime
[INFO] |  |  |  |  |  |        \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.8.22:runtime
[INFO] |  |  |  |  |  +- io.grpc:grpc-opentelemetry:jar:1.64.0:compile
[INFO] |  |  |  |  |  |  \- com.google.auto.value:auto-value-annotations:jar:1.10.4:runtime
[INFO] |  |  |  |  |  +- io.grpc:grpc-protobuf:jar:1.64.0:compile
[INFO] |  |  |  |  |  |  +- com.google.api.grpc:proto-google-common-protos:jar:2.29.0:compile
[INFO] |  |  |  |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.64.0:runtime
[INFO] |  |  |  |  |  +- io.grpc:grpc-rls:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-services:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-servlet:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-servlet-jakarta:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-stub:jar:1.64.0:compile
[INFO] |  |  |  |  |  +- io.grpc:grpc-testing:jar:1.64.0:compile
[INFO] |  |  |  |  |  \- io.grpc:grpc-util:jar:1.64.0:compile
[INFO] |  |  |  |  \- io.netty:netty-tcnative-boringssl-static:jar:2.0.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-tcnative-classes:jar:2.0.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.65.Final:compile
[INFO] |  |  |  |     +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.65.Final:compile
[INFO] |  |  |  |     \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.65.Final:compile
[INFO] |  |  |  +- com.tencent.polaris:connector-consul:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.ecwid.consul:consul-api:jar:1.4.5:compile
[INFO] |  |  |  |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  +- com.tencent.polaris:connector-composite:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:registry-memory:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.google.protobuf:protobuf-java-util:jar:3.21.7:compile
[INFO] |  |  |  |     +- com.google.errorprone:error_prone_annotations:jar:2.5.1:compile
[INFO] |  |  |  |     +- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  |  |     \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  |  +- com.tencent.polaris:flow-cache-expired:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-router-factory:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:polaris-router-client:jar:2.0.0.0:compile
[INFO] |  |  |  |     \- com.tencent.polaris:polaris-router-api:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:loadbalancer-random:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:loadbalancer-ringhash:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-assembly-factory:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-assembly-client:jar:2.0.0.0:compile
[INFO] |  |  |  |  |  \- com.tencent.polaris:polaris-assembly-api:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.tencent.polaris:trace-otel:jar:2.0.0.0:compile
[INFO] |  |  |  |     \- io.opentelemetry:opentelemetry-api:jar:1.25.0:compile
[INFO] |  |  |  |        \- io.opentelemetry:opentelemetry-context:jar:1.25.0:compile
[INFO] |  |  |  \- com.tencent.polaris:event-tsf:jar:2.0.0.0:compile
[INFO] |  |  +- com.tencent.polaris:stat-prometheus:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:stat-common:jar:2.0.0.0:compile
[INFO] |  |  |  +- com.tencent.polaris:polaris-model:jar:2.0.0.0:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-specification:jar:1.5.4:compile
[INFO] |  |  |  |  |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  |  |  +- com.tencent.polaris:polaris-protobuf:jar:2.0.0.0:compile
[INFO] |  |  |  |  \- com.google.protobuf:protobuf-java:jar:3.21.7:compile
[INFO] |  |  |  \- com.tencent.polaris:polaris-config:jar:2.0.0.0:compile
[INFO] |  |  |     \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.15.3:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-starter-aop:jar:3.0.0:compile
[INFO] |  |     \- org.aspectj:aspectjweaver:jar:1.9.9.1:compile
[INFO] |  +- com.tencent.cloud:spring-cloud-tencent-lossless-plugin:jar:2.0.0.0-2022.0.5:compile
[INFO] |  |  +- com.tencent.polaris:lossless-register:jar:2.0.0.0:compile
[INFO] |  |  |  \- com.tencent.polaris:lossless-common:jar:2.0.0.0:compile
[INFO] |  |  |     \- com.google.guava:guava:jar:32.1.1-jre:compile
[INFO] |  |  |        +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |        +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |        \- org.checkerframework:checker-qual:jar:3.33.0:compile
[INFO] |  |  +- com.tencent.polaris:lossless-deregister:jar:2.0.0.0:compile
[INFO] |  |  \- com.tencent.polaris:lossless-warmup:jar:2.0.0.0:compile
[INFO] |  \- joda-time:joda-time:jar:2.9.9:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-loadbalancer:jar:4.0.5:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-starter:jar:4.0.5:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-context:jar:4.0.5:compile
[INFO] |  |  \- org.springframework.security:spring-security-rsa:jar:1.0.12.RELEASE:compile
[INFO] |  |     \- org.bouncycastle:bcpkix-jdk18on:jar:1.73:compile
[INFO] |  |        +- org.bouncycastle:bcprov-jdk18on:jar:1.73:compile
[INFO] |  |        \- org.bouncycastle:bcutil-jdk18on:jar:1.73:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-loadbalancer:jar:4.0.5:compile
[INFO] |  |  +- io.projectreactor:reactor-core:jar:3.5.17:compile
[INFO] |  |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  |  \- io.projectreactor.addons:reactor-extra:jar:3.5.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-cache:jar:3.0.0:compile
[INFO] |  |  \- org.springframework:spring-context-support:jar:6.0.21:compile
[INFO] |  \- com.stoyanr:evictor:jar:1.0.0:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-openfeign:jar:4.0.6:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-openfeign-core:jar:4.0.6:compile
[INFO] |  |  +- io.github.openfeign.form:feign-form-spring:jar:3.8.0:compile
[INFO] |  |  |  \- io.github.openfeign.form:feign-form:jar:3.8.0:compile
[INFO] |  |  \- commons-fileupload:commons-fileupload:jar:1.5:compile
[INFO] |  |     \- commons-io:commons-io:jar:2.11.0:compile
[INFO] |  +- org.springframework.cloud:spring-cloud-commons:jar:4.0.5:compile
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:6.1.9:compile
[INFO] |  +- io.github.openfeign:feign-core:jar:12.5:compile
[INFO] |  \- io.github.openfeign:feign-slf4j:jar:12.5:compile
[INFO] |     \- org.slf4j:slf4j-api:jar:2.0.4:compile
[INFO] +- org.springframework.cloud:spring-cloud-starter-bootstrap:jar:4.0.5:compile
[INFO] +- org.springframework.boot:spring-boot-starter:jar:3.0.0:compile
[INFO] |  +- org.springframework.boot:spring-boot:jar:3.0.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-autoconfigure:jar:3.0.0:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-logging:jar:3.0.0:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.4.5:compile
[INFO] |  |  |  \- ch.qos.logback:logback-core:jar:1.4.5:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.20.0:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.20.0:compile
[INFO] |  |  \- org.slf4j:jul-to-slf4j:jar:2.0.4:compile
[INFO] |  +- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  +- org.springframework:spring-core:jar:6.0.21:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:6.0.21:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.33:compile
[INFO] \- org.projectlombok:lombok:jar:1.18.28:compile

**Comment by ranan05** [comment]
[polaris.log](https://github.com/user-attachments/files/18272863/polaris.log)

**Comment by SkyeBeFreeman** [comment]
> 用的是北极星国内公共集群，address: grpc://11.154.192.97:8081 注册都是是成功的，就是心跳上报失败 @SkyeBeFreeman

@ranan05 这个是哪里的集群？8091才是北极星的端口号。
