### ISSUE TITLE
熔断组件，在项目不依赖openFeign时会启动报错

### ISSUE THREAD

**Issue by vinartis** [Tencent/spring-cloud-tencent#268]
**Describe the bug**
`
Caused by: java.lang.ClassNotFoundException: org.springframework.cloud.openfeign.FeignAutoConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_251]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_251]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_251]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_251]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_251]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:284) ~[spring-core-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:324) ~[spring-core-5.2.13.RELEASE.jar:5.2.13.RELEASE]
	... 25 common frames omitted

@ConditionalOnProperty(value = "spring.cloud.polaris.circuitbreaker.enabled",
		havingValue = "true", matchIfMissing = true)
@Configuration(proxyBeanMethods = false)
@AutoConfigureAfter(PolarisContextAutoConfiguration.class)
@AutoConfigureBefore(FeignAutoConfiguration.class)
public class PolarisFeignClientAutoConfiguration {

	@Bean
	public ConsumerAPI consumerAPI(SDKContext context) {
		return DiscoveryAPIFactory.createConsumerAPIByContext(context);
	}

	@Bean
	@Order(HIGHEST_PRECEDENCE)
	public PolarisFeignBeanPostProcessor polarisFeignBeanPostProcessor(
			ConsumerAPI consumerAPI) {
		return new PolarisFeignBeanPostProcessor(consumerAPI);
	}

}
`

**To Reproduce**
只依赖如下组件
`      <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tencent.cloud</groupId>
            <artifactId>spring-cloud-starter-tencent-polaris-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.tencent.cloud</groupId>
            <artifactId>spring-cloud-starter-tencent-polaris-circuitbreaker</artifactId>
        </dependency>`

**Expected behavior**
可以正常启动，

**Comment by SkyeBeFreeman** [comment]
目前熔断模块必须与feign同时使用，你认为如何实现比较好呢？可以一起讨论下哈

**Comment by lltx** [comment]
https://github.com/Tencent/spring-cloud-tencent/issues/241


支持了 resttemplate 这个问题就好解决了

**Comment by SkyeBeFreeman** [comment]
这边临时做了规避方法，即在`PolarisFeignClientAutoConfiguration`内添加`@ConditionalOnClass(name = "org.springframework.cloud.openfeign.FeignAutoConfiguration")`，如果没有引入openfeign依赖时，则不进行自动配置。后续计划在接入北极星监控时，会将feign从熔断模块独立出来，彻底规避这个问题。
