### ISSUE TITLE
polaris-router-grayrelease-example application run failed

### ISSUE THREAD

**Issue by salahgao** [Tencent/spring-cloud-tencent#345]
**Describe the bug**
polaris-router-grayrelease-example application run failed。

2022-06-29 15:55:13.787  INFO 10196 --- [           main] .c.p.r.g.g.GrayReleaseGatewayApplication : No active profile set, falling back to default profiles: default
2022-06-29 15:55:14.574 ERROR 10196 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724) ~[na:1.8.0_181]
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531) ~[na:1.8.0_181]

[exception01.txt](https://github.com/Tencent/spring-cloud-tencent/files/9008539/exception01.txt)

**Environment**
Version: [933d573](https://github.com/Tencent/spring-cloud-tencent/commit/933d573c6401554a95f137d042b6901d7a59cff2)

**Additional context**
1.5.3-Hoxton.SR9 is ok。

**Comment by SkyeBeFreeman** [comment]
Thx for reporting. I will check and fix this.

**Comment by SkyeBeFreeman** [comment]
Just pull the newest code.
