### ISSUE TITLE
sct启动报java.lang.IllegalArgumentException: file group cannot be empty.

### ISSUE THREAD

**Issue by xingducai** [Tencent/spring-cloud-tencent#363]
sct版本: 1.5.3-2021.0.2
问题 ： sct启动报java.lang.IllegalArgumentException: file group cannot be empty.
	at com.tencent.polaris.configuration.client.util.ConfigFileUtils.checkConfigFileMetadata(ConfigFileUtils.java:16) ~[polaris-configuration-client-1.6.1.jar:na]
	at com.tencent.polaris.configuration.client.DefaultConfigFileService.getConfigPropertiesFile(DefaultConfigFileService.java:45) ~[polaris-configuration-client-1.6.1.jar:na]
	at com.tencent.polaris.configuration.client.DefaultConfigFileService.getConfigPropertiesFile(DefaultConfigFileService.java:40) ~[polaris-configuration-client-1.6.1.jar:na]
	at com.tencent.cloud.polaris.config.adapter.PolarisConfigFileLocator.loadPolarisPropertySource(PolarisConfigFileLocator.java:187)

**Comment by xingducai** [comment]
如果出现上面的问题，你需要检查一下bootstrap.yml 是否配置了spring:application:name

**Comment by SkyeBeFreeman** [comment]
可以按照这个文档[Spring Cloud Tencent Config 使用文档 - 模块简介](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E6%A8%A1%E5%9D%97%E7%AE%80%E4%BB%8B)的注意事项第2点进行检查。

**Comment by xingducai** [comment]
为什么我在application.yml配置了spring.application.name不行呢？
因为PolarisContextProperties.java 配置中的spring.cloud.polaris.service 默认取值 ${spring.application.name}

**Comment by xingducai** [comment]
@SkyeBeFreeman  

> 可以按照这个文档[Spring Cloud Tencent Config 使用文档 - 模块简介](https://github.com/Tencent/spring-cloud-tencent/wiki/Spring-Cloud-Tencent-Config-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E6%A8%A1%E5%9D%97%E7%AE%80%E4%BB%8B)的注意事项第2点进行检查。

**Comment by SkyeBeFreeman** [comment]
> 为什么我在application.yml配置了spring.application.name不行呢？
> 因为PolarisContextProperties.java 配置中的spring.cloud.polaris.service 默认取值 ${spring.application.name}

bootstrap的阶段无法读取到`application.yml`的配置。
