### ISSUE TITLE
提取system-metadata-router-keys和allMetadata异常

### ISSUE THREAD

**Issue by davionchen** [Tencent/spring-cloud-tencent#624]
**Describe the bug**

提取system-metadata-router-keys和allMetadata异常

**To Reproduce**

复现过程：
1、跳过SpringMVC容器，直接触发PolarisAutoServiceRegistration注册
2、执行如下代码；
```java
  DefaultRequest<RequestDataContext> lbRequest = new DefaultRequest(new RequestDataContext(buildRequestData(parm), hint));
            Set<LoadBalancerLifecycle> supportedLifecycleProcessors = LoadBalancerLifecycleValidator.getSupportedLifecycleProcessors(this.loadBalancerClientFactory.getInstances(serviceId, LoadBalancerLifecycle.class), RequestDataContext.class, ResponseData.class, ServiceInstance.class);
            supportedLifecycleProcessors.forEach((lifecycle) -> {
                lifecycle.onStart(lbRequest);
            });
            ServiceInstance instance = this.loadBalancerClient.choose(serviceId,lbRequest);



  private RequestData buildRequestData(Map<String, Object> parm) {
        HttpHeaders requestHeaders = new HttpHeaders();
        Map<String,String> headers = (Map)parm.get(RegisterConstant.REGISTER_PARAM_HEADER);
        if(headers==null){
            headers = new HashMap<String,String>();
        }
        headers.put("content-type", "application/json");
        headers.put("content-language", "zh-CN, zh, en");
        headers.put("connection", "close");

        headers.forEach((key, value) -> {
            ArrayList list = new ArrayList();
            list.add(value);
            requestHeaders.put(key, list);
        });
        return new RequestData(HttpMethod.resolve((String)parm.get(RegisterConstant.REGISTER_PARAM_METHOD)), URI.create((String)parm.get(RegisterConstant.REGISTER_PARAM_URL)), requestHeaders, (MultiValueMap)null, new HashMap());
    }


```

3、出现异常, 从http header 中找标签system-metadata-router-keys和allMetadata  异常

```
2022-09-22 17:36:11.677|ERROR|CCBS|20220920CCB000000000000000000002|defaultEventExecutorGroup-4-1|12023|67|serviceDiscovery exception -> {}
java.lang.NullPointerException: null
        at com.tencent.cloud.polaris.router.interceptor.MetadataRouterRequestInterceptor.apply(MetadataRouterRequestInterceptor.java:50) ~[spring-cloud-starter-tencent-polaris-router-1.7.0-2020.0.5.jar:1.7.0-2020.0.5]
        at com.tencent.cloud.polaris.router.PolarisRouterServiceInstanceListSupplier.processRouterRequestInterceptors(PolarisRouterServiceInstanceListSupplier.java:175) ~[spring-cloud-starter-tencent-polaris-router-1.7.0-2020.0.5.jar:1.7.0-2020.0.5]
        at com.tencent.cloud.polaris.router.PolarisRouterServiceInstanceListSupplier.doRouter(PolarisRouterServiceInstanceListSupplier.java:146) ~[spring-cloud-starter-tencent-polaris-router-1.7.0-2020.0.5.jar:1.7.0-2020.0.5]
        at com.tencent.cloud.polaris.router.PolarisRouterServiceInstanceListSupplier.get(PolarisRouterServiceInstanceListSupplier.java:107) ~[spring-cloud-starter-tencent-polaris-router-1.7.0-2020.0.5.jar:1.7.0-2020.0.5]
        at org.springframework.cloud.loadbalancer.core.RetryAwareServiceInstanceListSupplier.get(RetryAwareServiceInstanceListSupplier.java:53) ~[spring-cloud-loadbalancer-3.0.5.jar:3.0.5]
        at com.tencent.cloud.polaris.loadbalancer.PolarisLoadBalancer.choose(PolarisLoadBalancer.java:90) ~[spring-cloud-tencent-polaris-loadbalancer-1.7.0-2020.0.5.jar:1.7.0-2020.0.5]
        at com.tencent.cloud.polaris.loadbalancer.PolarisLoadBalancer.choose(PolarisLoadBalancer.java:54) ~[spring-cloud-tencent-polaris-loadbalancer-1.7.0-2020.0.5.jar:1.7.0-2020.0.5]
        at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.choose(BlockingLoadBalancerClient.java:150) ~[spring-cloud-loadbalancer-3.0.5.jar:3.0.5]
        at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient$$FastClassBySpringCGLIB$$e8a54518.invoke(<generated>) ~[spring-cloud-loadbalancer-3.0.5.jar:3.0.5]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.6.jar:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.6.jar:5.3.6]
        at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient$$EnhancerBySpringCGLIB$$9c4d5caf.choose(<generated>) ~[spring-cloud-loadbalancer-3.0.5.jar:3.0.5]
  
```

**Environment**
- SCT:1.7.0-2020.5

**Additional context**

**Comment by lepdou** [comment]
fixed #634
